# Generated by Django 3.1.5 on 2022-11-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_signal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('size_of_video', models.IntegerField(default=0)),
                ('video_title', models.CharField(max_length=200)),
                ('subscription_period', models.IntegerField(default=0)),
                ('priority', models.CharField(max_length=20)),
                ('priority_timings', models.CharField(max_length=20)),
                ('junction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_signal.signaldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
