# Generated by Django 3.1.5 on 2022-11-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_signal', '0002_auto_20221122_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='video_duration',
            field=models.CharField(default='00000', max_length=264),
        ),
    ]
