# Generated by Django 3.1.5 on 2022-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_signal', '0003_videodetails_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_duration',
            field=models.CharField(max_length=264),
        ),
    ]
